const SUPABASE_URL='https://uxsejwqzxmftyqfncmgf.supabase.co';
const SUPABASE_KEY='sb_publishable_7jNw8dRPfmzGo8xJ6SXo-w_rivj0GKd';
const client=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let mode=new URLSearchParams(location.search).get('mode')==='signup'?'signup':'signin';
const $=id=>document.getElementById(id),form=$('authForm'),alertBox=$('alert');
function alertMsg(msg,type='error'){alertBox.textContent=msg;alertBox.className=`alert show ${type}`}
function setMode(m){mode=m;const up=m==='signup';$('signinTab').classList.toggle('active',!up);$('signupTab').classList.toggle('active',up);$('businessField').style.display=up?'block':'none';$('forgot').style.display=up?'none':'inline';$('authTitle').textContent=up?'Create your BCK account.':'Welcome bck.';$('authCopy').textContent=up?'Start with a merchant account. You can add campaigns next.':'Sign in to your BCK merchant account.';$('submitBtn').textContent=up?'Create account ↗':'Sign in ↗';$('password').autocomplete=up?'new-password':'current-password';alertBox.className='alert'}
$('signinTab').onclick=()=>setMode('signin');$('signupTab').onclick=()=>setMode('signup');setMode(mode);
$('togglePassword').onclick=()=>{const p=$('password');p.type=p.type==='password'?'text':'password';$('togglePassword').textContent=p.type==='password'?'SHOW':'HIDE'};
form.onsubmit=async e=>{e.preventDefault();$('submitBtn').disabled=true;const email=$('email').value.trim(),password=$('password').value,business=$('business').value.trim();try{if(mode==='signup'){if(!business)throw new Error('Enter your business name.');const {data,error}=await client.auth.signUp({email,password,options:{data:{business_name:business},emailRedirectTo:new URL('auth.html',location.href).href}});if(error)throw error;if(data.session){location.href='dashboard.html'}else alertMsg('Account created. Check your email to confirm your address, then sign in.','success')}else{const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;location.href='dashboard.html'}}catch(err){alertMsg(err.message||'Something went wrong.')}finally{$('submitBtn').disabled=false}};
$('forgot').onclick=async()=>{const email=$('email').value.trim();if(!email)return alertMsg('Enter your email first.');const redirect=new URL('auth.html',location.href).href;const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:redirect});if(error)alertMsg(error.message);else alertMsg('Password reset email sent.','success')};
(async()=>{const {data}=await client.auth.getSession();if(data.session && mode==='signin')location.href='dashboard.html'})();
