(()=>{
'use strict';
const dqs=(s,r=document)=>r.querySelector(s),dqa=(s,r=document)=>[...r.querySelectorAll(s)];
const params=()=>new URLSearchParams(location.search);const currentView=()=>params().get('view')||'overview';
const preview=()=>params().get('preview')==='1';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const live={uid:null,profile:null,campaigns:[],events:[],coupons:[],booted:false,sub:null,range:'7D',analyticsTab:'traffic',refreshTimer:null,migrated:false};
const getLocal=()=>{try{return JSON.parse(localStorage.getItem('bck_console_state')||'{}')}catch{return {}}};
const setLocal=p=>localStorage.setItem('bck_console_state',JSON.stringify({...getLocal(),...p}));
function toast(msg){if(typeof window.toast==='function')return window.toast(msg);let e=dqs('#bckLiveToast');if(!e){e=document.createElement('div');e.id='bckLiveToast';e.className='bck-v2-toast';document.body.append(e)}e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2300)}
function fmtDate(d){return new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d))}
function isToday(v){const a=new Date(v),b=new Date();return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function startDays(days){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(days-1));return d}
function activeCampaign(){return live.campaigns.find(c=>c.status==='active')||null}
function mirrorCampaigns(){const state=getLocal();const mapped=live.campaigns.map(c=>({id:c.id,name:c.name,description:c.description||'',games:Array.isArray(c.games)?c.games:[],rewardMode:c.reward_mode||'Hybrid',status:c.status,plays:live.events.filter(e=>e.campaign_id===c.id&&e.event_type==='play').length,wins:live.events.filter(e=>e.campaign_id===c.id&&e.event_type==='win').length,redeemed:live.events.filter(e=>e.campaign_id===c.id&&e.event_type==='redeem').length,meta:{start:c.start_date||'',end:c.end_date||'',maxPlays:c.max_plays_per_person??1,cooldown:c.cooldown_minutes||0},gameConfigs:c.game_configs||{}}));setLocal({...state,campaigns:mapped,activity:dailyRows(370).map(x=>({date:x.iso,plays:x.plays,wins:x.wins}))})}
// Legacy browser drafts are never silently imported into another merchant account.
async function allRows(query){const rows=[];for(let start=0;;start+=1000){const r=await query().range(start,start+999);if(r.error)throw r.error;rows.push(...r.data);if(r.data.length<1000)return rows}}
async function loadLive(){if(preview()){normalizePreview();return}if(!live.uid)throw new Error('Sign in required');if(live.loading)return live.loading;live.loading=(async()=>{const since=startDays(370).toISOString();const [p,c,e,co]=await Promise.all([client.from('profiles').select('*').eq('id',live.uid).maybeSingle(),allRows(()=>client.from('campaigns').select('*').eq('merchant_id',live.uid).order('created_at',{ascending:false}).order('id')),allRows(()=>client.from('activity_events').select('*').eq('merchant_id',live.uid).gte('created_at',since).order('created_at').order('id')),allRows(()=>client.from('coupons').select('*').eq('merchant_id',live.uid).order('created_at',{ascending:false}).order('id'))]);if(p.error)throw p.error;live.profile=p.data;live.campaigns=c;live.events=e;live.coupons=co;mirrorCampaigns()})();try{return await live.loading}finally{live.loading=null}}
function scheduleRefresh(){clearTimeout(live.refreshTimer);live.refreshTimer=setTimeout(async()=>{try{await loadLive();enhance()}catch{toast('Live update unavailable. Use Refresh data to retry.')}},120)}
function subscribe(){if(preview()||!live.uid||live.sub)return;live.sub=client.channel('bck-merchant-'+live.uid).on('postgres_changes',{event:'*',schema:'public',table:'activity_events',filter:`merchant_id=eq.${live.uid}`},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'coupons',filter:`merchant_id=eq.${live.uid}`},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'campaigns',filter:`merchant_id=eq.${live.uid}`},scheduleRefresh).subscribe()}
async function bootstrap(){if(live.booted)return;live.booted=true;if(preview()){normalizePreview();setTimeout(enhance,30);return}const {data:{session:s}}=await client.auth.getSession();if(!s)return;live.uid=s.user.id;try{await loadLive()}catch{toast('Could not load merchant data. Use Refresh data to retry.')}try{if(live.profile?.business_name)businessName=live.profile.business_name}catch{}if(typeof render==='function')render();subscribe();setTimeout(enhance,30)}
function normalizePreview(){const s=getLocal(),arr=s.campaigns||[];let seen=false;arr.forEach(c=>{if(c.status==='active'){if(seen)c.status='paused';else seen=true}});setLocal({...s,campaigns:arr});live.campaigns=arr.map((c,i)=>({id:c.id||`preview-${i}`,merchant_id:'preview',name:c.name,description:c.description,games:c.games||[],reward_mode:c.rewardMode||'Hybrid',status:c.status||'draft',game_configs:c.gameConfigs||{},max_plays_per_person:c.meta?.maxPlays||1,cooldown_minutes:c.meta?.cooldown||0,created_at:new Date().toISOString()}));live.events=[];live.coupons=[];live.profile={business_name:'BCK Preview',preferred_language:'en'}}
function placeBrandAndLanguage(){const side=dqs('.console-sidebar'),brand=dqs('.console-sidebar .brand'),lang=dqs('#bckLanguage');if(!side||!brand)return;let row=dqs('.bck-brand-row',side);if(!row){row=document.createElement('div');row.className='bck-brand-row';brand.parentNode.insertBefore(row,brand);row.append(brand)}if(!brand.querySelector('img')){brand.innerHTML='<img src="assets/bck-wordmark.svg" alt="bck.">'}brand.style.background='none';if(lang&&lang.parentElement!==row)row.append(lang);if(lang){const code=(localStorage.getItem('bck_language')||live.profile?.preferred_language||'en').toUpperCase();const strong=dqs('.bck-lang-trigger strong',lang);if(strong)strong.textContent=code}const chip=dqs('.store-chip',side);if(chip&&live.profile?.logo_url&&!dqs('.merchant-logo',chip)){chip.classList.add('has-logo');const img=document.createElement('img');img.className='merchant-logo';img.src=live.profile.logo_url;img.alt='Store logo';chip.prepend(img)}}
function dailyRows(days=7,from=null,to=null){let start=from?new Date(from+'T00:00:00'):startDays(days),end=to?new Date(to+'T23:59:59'):new Date();const map=new Map();for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const iso=d.toISOString().slice(0,10);map.set(iso,{iso,label:new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'2-digit'}).format(d),plays:0,wins:0,scans:0,redeems:0,returns:0,unique:new Set(),issued:0})}for(const e of live.events){const dt=new Date(e.created_at);if(dt<start||dt>end)continue;const iso=new Date(dt.getFullYear(),dt.getMonth(),dt.getDate()).toISOString().slice(0,10),r=map.get(iso);if(!r)continue;if(e.event_type==='play')r.plays++;if(e.event_type==='win')r.wins++;if(e.event_type==='scan'){r.scans++;if(e.visitor_id)r.unique.add(e.visitor_id)}if(e.event_type==='redeem')r.redeems++;if(e.event_type==='return')r.returns++}for(const c of live.coupons){const dt=new Date(c.issued_at||c.created_at);if(dt<start||dt>end)continue;const iso=new Date(dt.getFullYear(),dt.getMonth(),dt.getDate()).toISOString().slice(0,10);if(map.has(iso))map.get(iso).issued++}return [...map.values()].map(r=>({...r,unique:r.unique.size}))}
function chartHTML(rows,aKey,bKey,aLabel,bLabel,third=null){
  if(!rows.length)return '<p>No activity in this range.</p>';
  const series=[[aKey,aLabel,'#6558ff'],[bKey,bLabel,'#47562b'],...(third?[[third,'Wins','#111111']]:[])],W=720,H=260,L=44,R=24,T=24,B=40;
  const max=Math.max(2,...rows.flatMap(r=>series.map(([k])=>+r[k]||0))),x=i=>rows.length===1?W/2:L+i*(W-L-R)/(rows.length-1),y=v=>T+(max-v)*(H-T-B)/max,step=Math.max(1,Math.ceil(rows.length/6));
  return `<div class="bck-chart-key">${series.map(([,name,color])=>`<span><i style="background:${color}"></i>${esc(name)}</span>`).join('')}</div><div class="bck-line-scroll" tabindex="0" aria-label="Daily activity chart"><svg class="bck-line-chart" viewBox="0 0 ${W} ${H}" aria-label="Daily counts"><title>Daily counts in the selected date range</title>${[0,.5,1].map(f=>`<line x1="${L}" x2="${W-R}" y1="${y(max*f)}" y2="${y(max*f)}" stroke="#ddd6ca"/><text x="${L-8}" y="${y(max*f)+4}" text-anchor="end">${Math.round(max*f)}</text>`).join('')}${series.map(([k,name,color])=>`<path fill="none" stroke="${color}" stroke-width="2" d="${rows.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(+r[k]||0)}`).join(' ')}"/>${rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(+r[k]||0)}" r="4" fill="${color}" ${r[k]?'tabindex="0"':''} data-chart-tip="${esc(r.iso+' · '+name+' · '+(+r[k]||0))}"><title>${esc(r.iso+' · '+name+' · '+(+r[k]||0))}</title></circle>`).join('')}`).join('')}${rows.map((r,i)=>i%step===0||i===rows.length-1?`<text x="${x(i)}" y="${H-12}" text-anchor="middle">${esc(r.label)}</text>`:'').join('')}</svg></div><p class="bck-chart-tooltip" role="status">Tap or focus a point for its date, metric and value.</p>`;
}
function setMetricCards(values){const cards=dqa('.grid4>.metric');values.forEach((v,i)=>{if(!cards[i])return;const strong=dqs('strong',cards[i]);if(strong)strong.textContent=v.value;const span=dqs('span',cards[i]);if(span&&v.sub)span.textContent=v.sub})}
function enhanceOverview(){if(currentView()!=='overview')return;const today=live.events.filter(e=>isToday(e.created_at)),scans=today.filter(e=>e.event_type==='scan').length,plays=today.filter(e=>e.event_type==='play').length,redeems=today.filter(e=>e.event_type==='redeem').length,returns=today.filter(e=>e.event_type==='return').length,unique=new Set(today.filter(e=>e.event_type==='scan').map(e=>e.visitor_id).filter(Boolean)).size;setMetricCards([{value:scans,sub:'Today'},{value:plays,sub:'Today'},{value:redeems,sub:'Today'},{value:unique?`${Math.round(returns/unique*100)}%`:'0%',sub:'Come-BCK visitors'}]);const panel=dqs('.panel.chart');if(panel){const old=dqs('.bck-live-chart,.empty-chart,.live-overview-chart',panel);if(old)old.outerHTML=`<div class="live-overview-chart">${chartHTML(dailyRows(7),'plays','wins','Plays','Wins')}</div>`}const funnel=dqa('.funnel-stat strong');[scans,plays,today.filter(e=>e.event_type==='win').length,returns].forEach((v,i)=>{if(funnel[i])funnel[i].textContent=v});const ac=activeCampaign(),banner=dqs('.status-banner');if(banner){const strong=dqs('strong',banner),span=dqs('span',banner);if(strong)strong.textContent=ac?ac.name:'No active campaign';if(span)span.textContent=ac?`${(ac.games||[]).length} game(s) · ${ac.reward_mode||'Hybrid'}`:'Your permanent QR is ready. Activate a campaign to start serving games.'}const right=dqs('.grid2>section:nth-child(2)');if(right){dqs('.active-campaign-action',right)?.remove();const box=document.createElement('div');box.className='active-campaign-action';box.innerHTML=ac?`<div><strong>Pause active campaign</strong><small>${esc(ac.name)} is currently behind your permanent QR.</small></div><button class="btn small" data-live-pause="${ac.id}">Pause</button>`:`<div><strong>No active campaign</strong><small>Your QR will show the fallback screen until you activate one.</small></div><button class="btn small" data-go-live="campaigns">Open campaigns</button>`;right.append(box);dqs('[data-live-pause]',box)?.addEventListener('click',async()=>{await setStatus(ac.id,'paused')});dqs('[data-go-live]',box)?.addEventListener('click',()=>navigate('campaigns'))}const count=dqs('.grid2>section:nth-child(2)>.panel strong');if(count)count.textContent=live.campaigns.length}
function navigate(v){try{go(v)}catch{history.pushState({},'',`dashboard.html?view=${v}`);if(typeof render==='function')render();setTimeout(enhance,20)}}
async function setStatus(id,status){if(preview()){const s=getLocal(),arr=s.campaigns||[],idx=arr.findIndex(x=>String(x.id)===String(id)||x.name===live.campaigns.find(c=>c.id===id)?.name);if(status==='active')arr.forEach((c,i)=>{if(i!==idx&&c.status==='active')c.status='paused'});if(arr[idx])arr[idx].status=status;setLocal({...s,campaigns:arr});normalizePreview();if(typeof render==='function')render();return setTimeout(enhance,20)}const {error}=await client.rpc('set_campaign_status',{p_campaign_id:id,p_status:status});if(error)return toast(error.message);toast(status==='active'?'Campaign is now live behind your permanent QR.':`Campaign ${status}.`);await loadLive();if(typeof render==='function')render();setTimeout(enhance,20)}
function enhanceCampaigns(){if(currentView()!=='campaigns')return;const rows=dqa('.campaign-row');rows.forEach((row,i)=>{const c=live.campaigns[i];if(!c)return;row.dataset.campaignId=c.id;const status=dqs('.status',row);if(status){status.textContent=c.status.toUpperCase();status.className=`status ${c.status}`}});const filters=dqs('.toolbar .filters');if(filters&&!dqs('[data-live-filter="paused"]',filters)){['paused','ended'].forEach(k=>{if(dqs(`[data-extra-filter="${k}"]`,filters))return;const b=document.createElement('button');b.className='filter';b.dataset.liveFilter=k;b.textContent=k[0].toUpperCase()+k.slice(1);b.onclick=()=>{dqa('.toolbar .filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');dqa('.campaign-row').forEach(r=>r.style.display=r.dataset.status===k?'grid':'none')};filters.append(b)})}}
function campaignFromTarget(t){const row=t.closest('.campaign-row');if(row?.dataset.campaignId)return live.campaigns.find(c=>c.id===row.dataset.campaignId);const modal=t.closest('.bck-detail');const name=dqs('h2',modal)?.textContent;return live.campaigns.find(c=>c.name===name)}
async function interceptCampaignAction(e){const b=e.target.closest('[data-a],[data-act]');if(!b)return;const action=b.dataset.a||b.dataset.act;if(!['activate','resume','pause','end','delete'].includes(action))return;const c=campaignFromTarget(b);if(!c)return;e.preventDefault();e.stopImmediatePropagation();if(action==='delete'){if(!confirm(`Delete ${c.name}?`))return;if(preview()){const s=getLocal();s.campaigns=(s.campaigns||[]).filter(x=>x.name!==c.name);setLocal(s);normalizePreview()}else{const {error}=await client.from('campaigns').delete().eq('id',c.id).eq('merchant_id',live.uid);if(error)return toast(error.message);await loadLive()}dqs('#bckDetail')?.remove();if(typeof render==='function')render();return setTimeout(enhance,20)}if(action==='end'&&!confirm(`End ${c.name}? Customers will stop receiving this campaign.`))return;if((action==='activate'||action==='resume')&&activeCampaign()&&activeCampaign().id!==c.id&&!confirm(`${activeCampaign().name} is live now. Pause it and activate ${c.name}?`))return;dqs('#bckDetail')?.remove();await setStatus(c.id,action==='activate'||action==='resume'?'active':action)}
async function interceptSaveCampaign(e){const btn=e.target.closest('#saveCampaign');if(!btn||currentView()!=='new-campaign')return;e.preventDefault();e.stopImmediatePropagation();const name=dqs('#campaignName')?.value.trim();if(!name)return toast('Add a campaign name first.');const games=dqa('[data-game].selected').map(x=>x.dataset.game);if(!games.length)return toast('Choose at least one game.');const description=dqs('#campaignDescription')?.value.trim()||'',rewardMode=dqs('[data-reward-mode].selected')?.dataset.rewardMode||'Hybrid',dates=dqa('.wizard-panel[data-step="1"] input[type="date"]'),nums=dqa('.wizard-panel[data-step="1"] input[type="number"]'),launch=dqs('#launchNow')?.classList.contains('on');const controls={couponAutoExpiry:toggleByTitle('Coupon auto-expiry'),allowCouponCopy:toggleByTitle('Allow coupon code copy'),staffAssisted:toggleByTitle('Staff-assisted redemption')};const row={merchant_id:live.uid,name,description,games,reward_mode:rewardMode,status:'draft',start_date:dates[0]?.value||null,end_date:dates[1]?.value||null,max_plays_per_person:+nums[0]?.value||1,cooldown_minutes:+nums[1]?.value||0,location:dqs('.wizard-panel[data-step="1"] .field.full:last-child input')?.value||null,redemption_controls:controls,game_configs:window.BCKV2?.configs||{}};btn.disabled=true;if(preview()){const s=getLocal(),arr=s.campaigns||[];arr.unshift({id:`preview-${Date.now()}`,name,description,games,rewardMode,status:launch?'active':'draft',gameConfigs:row.game_configs,meta:{start:row.start_date,end:row.end_date,maxPlays:row.max_plays_per_person,cooldown:row.cooldown_minutes}});if(launch)arr.slice(1).forEach(c=>{if(c.status==='active')c.status='paused'});setLocal({...s,campaigns:arr});normalizePreview();btn.disabled=false;return navigate('campaigns')}const {data,error}=await client.from('campaigns').insert(row).select().single();if(error){btn.disabled=false;return toast(error.message)}if(launch){const {error:ae}=await client.rpc('set_campaign_status',{p_campaign_id:data.id,p_status:'active'});if(ae){btn.disabled=false;return toast(ae.message)}}await loadLive();btn.disabled=false;toast('Campaign saved.');navigate('campaigns')}
function toggleByTitle(title){const row=dqa('.toggle-row').find(r=>dqs('.toggle-copy strong',r)?.textContent.trim()===title);return !!dqs('.toggle.on',row)}
function publicLink(){return live.uid?`${location.origin}/play.html?merchant=${encodeURIComponent(live.uid)}`:`${location.origin}/play.html?merchant=preview`}
function enhanceQR(){if(currentView()!=='qr')return;const url=publicLink(),el=dqs('#qrCode'),urlEl=dqs('#qrUrl');if(urlEl)urlEl.textContent=url;if(el&&!el.dataset.liveQr){el.innerHTML='';new QRCode(el,{text:url,width:220,height:220,colorDark:live.profile?.qr_style?.color||'#111111',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.H});el.dataset.liveQr='1'}const prev=dqs('.qr-preview');if(prev&&!dqs('.qr-live-state',prev)){const ac=activeCampaign(),s=document.createElement('div');s.className=`qr-live-state ${ac?'active':'inactive'}`;s.textContent=ac?`● Live route: ${ac.name}`:'● No active campaign — fallback screen will show';prev.append(s);const stamp=document.createElement('div');stamp.className='brand-stamp';stamp.innerHTML='<span>Powered by</span><img src="assets/bck-wordmark.svg" alt="bck.">';prev.append(stamp)}const pill=dqs('.page-head .pill');if(pill)pill.textContent=`${live.events.filter(e=>e.event_type==='scan'&&isToday(e.created_at)).length} scans today`;dqa('[data-qr-color]').forEach(sw=>{sw.onclick=()=>{dqa('[data-qr-color]').forEach(x=>x.classList.remove('selected'));sw.classList.add('selected');if(el){el.innerHTML='';new QRCode(el,{text:url,width:220,height:220,colorDark:sw.dataset.qrColor,colorLight:'#fff',correctLevel:QRCode.CorrectLevel.H})}}});const actions=dqa('.qr-actions .btn');if(actions[0])actions[0].onclick=()=>savePDF(url);if(actions[1])actions[1].onclick=()=>saveQRImage();if(actions[2])actions[2].onclick=async()=>{try{await navigator.clipboard.writeText(url);toast('QR link copied.')}catch{toast(url)}};if(actions[3])actions[3].onclick=saveQRStyle;dqa('.border-option').forEach(b=>b.onclick=()=>{dqa('.border-option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const wrap=dqs('.qr-wrap');if(wrap){wrap.style.borderStyle=b.textContent.trim()==='Dashed'?'dashed':'solid';wrap.style.borderWidth=b.textContent.trim()==='Bold'?'6px':'3px';wrap.style.borderColor=b.textContent.trim()==='Violet'?'#6558FF':'#111'}})}
function qrDataURL(){const c=dqs('#qrCode canvas');if(c)return c.toDataURL('image/png');const img=dqs('#qrCode img');return img?.src||null}
function saveQRImage(){const data=qrDataURL();if(!data)return toast('QR is still loading.');const a=document.createElement('a');a.href=data;a.download='bck-permanent-qr.png';a.click()}
function savePDF(url){const data=qrDataURL();if(!data)return toast('QR is still loading.');if(!window.jspdf?.jsPDF)return toast('PDF library is still loading.');const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'});pdf.setFontSize(22);pdf.text(live.profile?.business_name||'BCK QR',105,32,{align:'center'});pdf.addImage(data,'PNG',60,48,90,90);pdf.setFontSize(11);pdf.text('Scan. Play. Win. Come bck.',105,150,{align:'center'});pdf.setFontSize(8);pdf.text(url,105,160,{align:'center',maxWidth:170});pdf.save('bck-permanent-qr.pdf')}
async function saveQRStyle(){const color=dqs('[data-qr-color].selected')?.dataset.qrColor||'#111111',frame=dqs('.border-option.selected')?.textContent.trim().toLowerCase()||'clean';if(preview())return toast('QR style saved for preview.');const {error}=await client.from('profiles').update({qr_style:{color,frame}}).eq('id',live.uid);if(error)return toast(error.message);live.profile.qr_style={color,frame};toast('QR style saved.')}
function rangeDates(){if(typeof live.range==='object')return {from:new Date(live.range.from+'T00:00:00'),to:new Date(live.range.to+'T23:59:59.999')};const hours=BCKHours.saved(live.profile,live.uid||'preview'),tz=hours?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,today=BCKHours.parts(new Date(),tz).date,from=new Date(today+'T00:00:00');from.setDate(from.getDate()-(({'1D':1,'7D':7,'30D':30,'90D':90,'1Y':365}[live.range]||7)-1));return {from,to:new Date(today+'T23:59:59.999')}}
function peakHTML(events,from,to,hours,timezone){
  const metric=live.peakMetric||'play',label={scan:'scans',play:'plays',redeem:'redemptions'}[metric],p=BCKHours.peak(events,{from:BCKInsights.day(from),to:BCKInsights.day(to),metric,schedule:hours,timezone}),max=Math.max(1,...p.bars.map(b=>b.value));
  return `<section class="panel bck-peak-panel"><div class="chart-head"><h2>Peak engagement</h2><label class="field">Metric<select id="peakMetric">${[['play','Plays'],['scan','Scans'],['redeem','Redemptions']].map(([v,n])=>`<option value="${v}" ${v===metric?'selected':''}>${n}</option>`).join('')}</select></label></div><p>Hourly ${label} · ${esc(p.timezone)}. Aggregated by hour of day across the selected dates.</p>${p.configured?'':`<p>Add business hours to tailor Peak Engagement. <a href="dashboard.html?view=company${preview()?'&preview=1':''}#businessHours">Add business hours →</a> Showing observed hours; timezone defaults to this browser until configured.</p>`}<div class="bck-hour-scroll" tabindex="0" aria-label="Hourly engagement chart"><div class="bck-hour-chart">${p.bars.length?p.bars.map(b=>`<button type="button" class="bck-hour-bar" data-chart-tip="${esc(b.label+' · '+b.value+' '+label)}" aria-label="${esc(b.label+' · '+b.value+' '+label)}"><span class="bck-hour-plot" style="--bar-height:${b.value/max*140}px"><span class="bck-hour-fill" style="height:${b.value/max*140}px"></span><strong>${b.value}</strong></span><span>${String(b.hour).padStart(2,'0')}–${String((b.hour+1)%24).padStart(2,'0')}</span><small>${b.part}</small></button>`).join(''):'<p>No activity for this metric in the selected hours.</p>'}</div></div><p class="bck-chart-tooltip" role="status">Tap or focus a bar for its hour and count.</p>${p.outside?`<p class="field-help">${p.outside} ${label} occurred outside configured opening hours and are excluded from this chart, not from totals.</p>`:''}</section>`;
}
function enhanceAnalytics(){
  if(currentView()!=='analytics')return;const content=dqs('.content');if(!content)return;
  const actions=dqs('.page-head .top-actions');dqs('.filters',actions)?.remove();
  const hours=BCKHours.saved(live.profile,live.uid||'preview'),timezone=hours?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone;
  const key=JSON.stringify([live.range,live.analyticsTab,params().get('campaign'),live.peakMetric,hours]);
  if(content._insightEvents===live.events&&content._insightCoupons===live.coupons&&content._insightKey===key)return;
  content._insightEvents=live.events;content._insightCoupons=live.coupons;content._insightKey=key;
  const {from,to}=rangeDates(),campaign=params().get('campaign')||'',m=BCKInsights.summarize(live.events,live.coupons,{from,to,campaign,timezone},Object.keys(BCKGames.games)),tab=live.analyticsTab;
  const pct=(a,b)=>b?(100*a/b).toFixed(1)+'%':'—',num=n=>n==null?'—':Number.isInteger(n)?String(n):n.toFixed(1);
  const metric=(label,value,sub='')=>`<section class="panel metric"><small>${esc(label)}</small><strong>${esc(value)}</strong><span>${esc(sub)}</span></section>`;
  const metrics=items=>`<div class="grid4">${items.map(x=>metric(...x)).join('')}</div>`;
  let cards,detail='',keys=['scans','plays'],labels=['Scans','Plays'];
  if(tab==='games'){
    cards=[['Plays',m.plays],['Completed games',num(m.completed),'Only tracked completions'],['Wins',m.wins],['Win rate',pct(m.wins,m.plays)]];
    keys=['plays','wins'];labels=['Plays','Wins'];
    detail=`<section class="bck-game-insights">${m.games.map(g=>`<details class="panel"><summary>${BCKGames.mark(g.game)}<span><strong>${esc(g.game)}</strong><small>${g.plays} plays · ${g.wins} wins · ${g.redeemed} redemptions</small></span></summary><dl><div><dt>Completions</dt><dd>${num(g.completions)}</dd></div><div><dt>Win rate</dt><dd>${pct(g.wins,g.plays)}</dd></div><div><dt>Rewards issued</dt><dd>${g.issued}</dd></div><div><dt>${g.game==='Perfect Pour'?'Average accuracy':g.game==='Pin the Bite'?'Average pieces':g.game==='Stack & Win'?'Average layers':'Average score'}</dt><dd>${num(g.average)}${g.game==='Perfect Pour'&&g.average!=null?'%':''}</dd></div></dl></details>`).join('')}</section>`;
  }else if(tab==='coupons'){
    cards=[['Coupons issued',m.issued],['Redeemed',m.redeemed,'From this issue cohort'],['Expired',m.expired,'Unused as of range end'],['Redemption rate',pct(m.redeemed,m.issued)]];
    keys=['issued','redeems'];labels=['Issued','Redemption events'];
    detail=metrics([['Average time to redeem',m.averageRedeemHours==null?'—':num(m.averageRedeemHours)+'h'],['Instant rewards',m.cs.filter(c=>c.reward_type==='instant').length],['Come-BCK rewards',m.comeback],['Come-BCK redeemed',m.comebackRedeemed]])+`<section class="panel"><h2>Reward performance</h2><p>Issue cohort: rewards created in the selected dates, redeemed by the range end.</p><div class="bck-reward-insights">${m.rewards.length?m.rewards.map(r=>`<article><strong>${esc(r.label)}</strong><small>${esc(r.game||'Unknown game')} · ${esc(live.campaigns.find(c=>c.id===r.campaign)?.name||'Archived campaign')} · ${r.type==='comeback'?'Come-BCK':'Instant'}</small><span>${r.issued} issued · ${r.redeemed} redeemed</span></article>`).join(''):'<p>No rewards in this range.</p>'}</div></section>`;
  }else if(tab==='retention'){
    cards=[['Unique players',m.uniquePlayers],['Repeat players',m.repeat,'Seen on multiple local dates'],['Return rate',pct(m.repeat,m.uniquePlayers)],['Come-BCK customers',m.comebackCustomers,'Redeemed rewards in issue cohort']];
    keys=['returns','redeems'];labels=['Return events','Redemption events'];
    detail=metrics([['Come-BCK redemption rate',pct(m.comebackRedeemed,m.comeback)],['Average days to return',num(m.averageReturnDays),'Reward issue → redemption'],['First-time customers',m.cohorts.first],['Repeat customers',m.cohorts.repeat]])+metrics([['VIP regulars',m.cohorts.vip,'3+ observed visit dates'],['At risk',m.cohorts.atRisk,'31–60 days inactive'],['Lapsed',m.cohorts.lapsed,'Over 60 days inactive']])+`<section class="panel"><h2>Observed customer cohorts</h2><p>Segments are exclusive, measured as of the selected range end across the available 370-day history. Anonymous browser identifiers are not verified people. No revenue or ROI is inferred.</p><div class="bck-cohort-bars">${Object.entries(m.cohorts).map(([k,v])=>`<div><span>${esc({first:'First-time',repeat:'Repeat',vip:'VIP',atRisk:'At risk',lapsed:'Lapsed'}[k])}</span><meter min="0" max="${Math.max(1,...Object.values(m.cohorts))}" value="${v}">${v}</meter><strong>${v}</strong></div>`).join('')}</div></section>`;
  }else{
    cards=[['QR scans',m.scans],['Unique scanners',m.uniqueScanners],['Plays',m.plays],['Completed games',num(m.completed),'Only tracked completions']];
    detail=metrics([['Winners',m.wins],['Win rate',pct(m.wins,m.plays)],['Scan → play',pct(m.plays,m.scans),'Event ratio; repeat plays can exceed 100%']])+peakHTML(m.es,from,to,hours,timezone);
  }
  content.innerHTML=`<section class="bck-analytics-controls"><div class="toolbar"><div class="filters">${['traffic','games','coupons','retention'].map(k=>`<button class="filter ${tab===k?'active':''}" data-insight-tab="${k}" aria-pressed="${tab===k}">${k[0].toUpperCase()+k.slice(1)}</button>`).join('')}</div></div><div class="toolbar"><label class="field">Campaign<select id="insightCampaign"><option value="">All campaigns</option>${live.campaigns.map(c=>`<option value="${esc(c.id)}" ${c.id===campaign?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label></div><section id="insightCustomPanel" ${typeof live.range==='object'?'':'hidden'} aria-label="Custom date range"><form id="insightCustom" class="bck-custom-range"><label class="field">From<input type="date" name="from" required min="${BCKInsights.day(startDays(370))}" max="${BCKInsights.day(new Date())}" value="${BCKInsights.day(from)}"></label><label class="field">To<input type="date" name="to" required min="${BCKInsights.day(startDays(370))}" max="${BCKInsights.day(new Date())}" value="${BCKInsights.day(to)}"></label><button class="btn" type="submit">Apply range</button><span role="status" id="rangeNotice"></span></form></section></section>${metrics(cards)}<section class="panel chart"><div class="chart-head"><h2>${tab==='retention'?'Return behaviour':'Daily activity'}</h2><span class="pill">LIVE DATA</span></div><p>${esc(BCKInsights.day(from))} → ${esc(BCKInsights.day(to))} · ${esc(timezone)}</p>${chartHTML(m.rows,keys[0],keys[1],labels[0],labels[1],tab==='traffic'?'wins':null)}</section>${detail}<p class="field-help">— means insufficient recorded data. Older games may not record completion or score. Refresh updates the same selected range.</p>`;
  let ranges=dqs('#bckDateRange');if(!ranges){ranges=document.createElement('div');ranges.id='bckDateRange';ranges.className='bck-date-range';ranges.setAttribute('aria-label','Analytics date range');actions.prepend(ranges)}
  ranges.innerHTML=['1D','7D','30D','90D','1Y'].map(k=>`<button class="filter ${live.range===k?'active':''}" data-insight-range="${k}" aria-pressed="${live.range===k}">${k}</button>`).join('')+`<button class="filter ${typeof live.range==='object'?'active':''}" id="insightCustomToggle" aria-expanded="${typeof live.range==='object'}">Custom</button>`;
  dqs('#insightCustomToggle').onclick=()=>{const panel=dqs('#insightCustomPanel');panel.hidden=!panel.hidden;dqs('#insightCustomToggle').setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)panel.querySelector('input').focus()};
  dqs('#peakMetric')?.addEventListener('change',e=>{live.peakMetric=e.target.value;enhanceAnalytics()});
  dqa('[data-chart-tip]',content).forEach(point=>{const show=()=>{const out=point.closest('.panel')?.querySelector('.bck-chart-tooltip');if(out)out.textContent=point.dataset.chartTip};point.addEventListener('pointerenter',show);point.addEventListener('focus',show);point.addEventListener('click',show)});
  dqa('[data-insight-tab]',content).forEach(b=>b.onclick=()=>{live.analyticsTab=b.dataset.insightTab;enhanceAnalytics();dqs(`[data-insight-tab="${live.analyticsTab}"]`)?.focus()});
  dqa('[data-insight-range]').forEach(b=>b.onclick=()=>{live.range=b.dataset.insightRange;enhanceAnalytics();dqs(`[data-insight-range="${live.range}"]`)?.focus()});
  dqs('#insightCustom').onsubmit=e=>{e.preventDefault();const f=e.currentTarget.elements.from.value,t=e.currentTarget.elements.to.value;if(f>t){dqs('#rangeNotice').textContent='End date must be on or after start date.';return}live.range={from:f,to:t};enhanceAnalytics()};
  dqs('#insightCampaign').onchange=e=>{const u=new URL(location.href);if(e.target.value)u.searchParams.set('campaign',e.target.value);else u.searchParams.delete('campaign');history.replaceState({},'',u);enhanceAnalytics()};
}
function enhanceCoupons(){if(currentView()!=='coupons')return;const cards=dqa('.grid3>.metric'),issued=live.coupons.length,redeemed=live.coupons.filter(c=>c.status==='redeemed').length,expired=live.coupons.filter(c=>c.status==='expired'||(c.expires_at&&new Date(c.expires_at)<new Date()&&c.status==='issued')).length;[issued,redeemed,expired].forEach((v,i)=>{const s=dqs('strong',cards[i]);if(s)s.textContent=v});const empty=dqs('.bck-coupon-list,.empty-state');if(!empty)return;const filter=dqs('.toolbar .filter.active')?.textContent.trim().toLowerCase()||'all';let rows=live.coupons.filter(c=>filter==='all'||(filter==='expired'?(c.status==='expired'||(c.expires_at&&new Date(c.expires_at)<new Date()&&c.status==='issued')):c.status===filter));empty.className='panel bck-coupon-list';empty.style.padding='18px';empty.innerHTML=rows.length?`<div class="bck-live-table">${rows.map(c=>`<div class="bck-live-row"><div><strong>${esc(c.reward_label)}</strong><small>${esc(c.game||'BCK reward')} · ${fmtDate(c.issued_at)}</small></div><div><span class="coupon-code-chip">${esc(c.code)}</span></div><div><strong>${esc(c.status)}</strong><small>${c.expires_at?`Expires ${fmtDate(c.expires_at)}`:'No expiry'}</small></div><div>${c.status==='issued'&&(!c.expires_at||new Date(c.expires_at)>new Date())?`<button class="btn small" data-redeem="${c.id}">Redeem</button>`:''}</div></div>`).join('')}</div>`:'<div class="live-empty"><strong>No matching coupons</strong>Rewards will appear here when customers win.</div>';dqa('.toolbar .filter').forEach(b=>b.onclick=()=>{dqa('.toolbar .filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');enhanceCoupons()});dqa('[data-redeem]').forEach(b=>b.onclick=async()=>{if(!confirm('Mark this coupon as redeemed?'))return;const {error}=await client.from('coupons').update({status:'redeemed'}).eq('id',b.dataset.redeem).eq('merchant_id',live.uid);if(error)return toast(error.message);toast('Coupon redeemed.');await loadLive();enhanceCoupons()})}
function customerStats(){const by={};live.events.filter(e=>e.visitor_id).forEach(e=>{const x=by[e.visitor_id]??={id:e.visitor_id,scans:0,returns:0,last:0,days:new Set(),wins:0,redeems:0};const t=new Date(e.created_at).getTime();x.last=Math.max(x.last,t);if(e.event_type==='scan'){x.scans++;x.days.add(new Date(e.created_at).toISOString().slice(0,10))}if(e.event_type==='return')x.returns++;if(e.event_type==='win')x.wins++;if(e.event_type==='redeem')x.redeems++});return Object.values(by)}
function enhanceCustomers(){if(currentView()!=='customers')return;const rows=customerStats(),returned=rows.filter(x=>x.returns>0).length,vip=rows.filter(x=>x.days.size>=3).length,atRisk=rows.filter(x=>x.last&&Date.now()-x.last>30*86400000).length;setMetricCards([{value:rows.length},{value:returned},{value:vip},{value:atRisk}]);const empty=dqs('.bck-customer-list,.empty-state');if(!empty)return;empty.className='panel bck-customer-list';empty.style.padding='0';empty.innerHTML=rows.length?`<div class="customer-row"><strong>Anonymous visitor</strong><strong>Visits</strong><strong>Rewards</strong><strong>Last seen</strong></div>${rows.sort((a,b)=>b.last-a.last).slice(0,100).map(x=>`<div class="customer-row"><span class="anon-id">${esc(x.id.slice(0,12))}…</span><span>${x.days.size}</span><span>${x.redeems}/${x.wins}</span><span>${fmtDate(x.last)}</span></div>`).join('')}`:'<div class="live-empty"><strong>No customer activity yet</strong>Anonymous customer profiles appear after real QR scans.</div>'}
function enhanceSettings(){if(currentView()!=='settings')return;const form=dqs('#settingsForm');if(form&&!form.dataset.live){form.dataset.live='1';const p=live.profile||{};if(form.elements.ownerName)form.elements.ownerName.value=p.owner_name||'';if(form.elements.businessName)form.elements.businessName.value=p.business_name||'';if(form.elements.phone)form.elements.phone.value=p.phone||'';if(form.elements.city)form.elements.city.value=p.city||'';if(form.elements.address)form.elements.address.value=p.address||'';if(form.elements.voice)form.elements.voice.value=p.default_campaign_voice||'Playful & short';form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();if(preview())return toast('Settings saved for preview.');const payload={owner_name:form.elements.ownerName.value.trim(),business_name:form.elements.businessName.value.trim(),phone:form.elements.phone.value.trim(),city:form.elements.city.value.trim(),address:form.elements.address.value.trim(),default_campaign_voice:form.elements.voice.value};const fb=dqs('#fallbackMessage'),fu=dqs('#fallbackUrl');if(fb)payload.fallback_message=fb.value.trim();if(fu)payload.fallback_url=fu.value.trim();const {error}=await client.from('profiles').update(payload).eq('id',live.uid);if(error)return toast(error.message);Object.assign(live.profile,payload);try{businessName=payload.business_name}catch{}toast('Settings saved.');if(typeof render==='function')render();setTimeout(enhance,20)},true)}const aside=dqs('.settings-grid aside');if(aside&&!dqs('.functional-fallback',aside)){const old=dqs('.settings-card.lime',aside);if(old)old.innerHTML=`<h2>QR fallback</h2><p>When no campaign is active, this is what customers see after scanning your permanent QR.</p><div class="functional-fallback"><div class="field"><label>Fallback message</label><textarea id="fallbackMessage" placeholder="No campaign right now — check back soon.">${esc(live.profile?.fallback_message||'')}</textarea></div><div class="field"><label>Optional fallback URL</label><input id="fallbackUrl" type="url" placeholder="https://yourmenu.com" value="${esc(live.profile?.fallback_url||'')}"></div><small class="bck-save-state">Saved with the main “Save changes” button.</small></div>`}const profile=dqs('.profile-head');if(profile&&live.profile?.logo_url){const av=dqs('.avatar',profile);if(av){const img=document.createElement('img');img.className='merchant-profile-logo';img.src=live.profile.logo_url;img.alt='Store logo';av.replaceWith(img)}}if(aside&&!dqs('.bck-support-actions',aside)){const wrap=document.createElement('div');wrap.className='bck-support-actions';wrap.innerHTML='<button class="bck-support-card bug" data-feedback-kind="bug"><i>🐞</i><span>Report a Bug</span></button><button class="bck-support-card feedback" data-feedback-kind="feedback"><i>💬</i><span>Submit Feedback</span></button>';aside.append(wrap);bindFeedbackButtons(wrap)}}
function bindFeedbackButtons(root=document){dqa('[data-feedback-kind]',root).forEach(b=>b.onclick=()=>openFeedback(b.dataset.feedbackKind))}
function openFeedback(kind){dqs('.bck-feedback-modal')?.remove();const m=document.createElement('div');m.className='bck-feedback-modal';m.innerHTML=`<div class="bck-feedback-dialog"><h2>${kind==='bug'?'Report a bug':'Submit feedback'}</h2><p>${kind==='bug'?'Tell us what went wrong and what you expected to happen.':'Tell us what would make BCK better for your business.'}</p><textarea id="feedbackText" placeholder="Write here…"></textarea><div class="bck-feedback-actions"><button class="btn ghost" data-close-feedback>Cancel</button><button class="btn ink" data-send-feedback>Submit</button></div></div>`;document.body.append(m);dqs('[data-close-feedback]',m).onclick=()=>m.remove();dqs('[data-send-feedback]',m).onclick=async()=>{const text=dqs('#feedbackText',m).value.trim();if(text.length<3)return toast('Please add a little more detail.');if(preview()){m.remove();return toast('Thanks — preview feedback captured locally.')}const {error}=await client.from('merchant_feedback').insert({merchant_id:live.uid,kind,message:text,page_url:location.href,user_agent:navigator.userAgent});if(error)return toast(error.message);m.remove();toast('Thank you. Submitted successfully.')}}
function enhanceSupport(){if(currentView()!=='support')return;const content=dqs('.content');if(content&&!dqs('.bck-support-actions',content)){const wrap=document.createElement('div');wrap.className='bck-support-actions';wrap.innerHTML='<button class="bck-support-card bug" data-feedback-kind="bug"><i>🐞</i><span>Report a Bug</span></button><button class="bck-support-card feedback" data-feedback-kind="feedback"><i>💬</i><span>Submit Feedback</span></button>';content.prepend(wrap);bindFeedbackButtons(wrap)}}
function enhanceNotifications(){if(currentView()!=='notifications')return;const empty=dqs('.bck-notification-list,.empty-state');if(!empty)return;const recent=[...live.events].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,30);empty.className='panel bck-notification-list';empty.style.padding='0';empty.innerHTML=recent.length?recent.map(e=>`<div class="notification-row"><span class="notification-icon">${e.event_type==='scan'?'▦':e.event_type==='play'?'🎮':e.event_type==='win'?'🎉':e.event_type==='redeem'?'✓':'↩'}</span><div><strong>${esc(e.event_type[0].toUpperCase()+e.event_type.slice(1))}${e.game?` · ${esc(e.game)}`:''}</strong><small>${e.reward_label?esc(e.reward_label):'Live customer activity'}</small></div><small>${new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short'}).format(new Date(e.created_at))}</small></div>`).join(''):'<div class="live-empty"><strong>No activity yet</strong>Real scans, plays, wins and redemptions will appear here.</div>'}
function refreshControl(){if(!['overview','coupons','analytics','customers'].includes(currentView()))return;const head=dqs('.page-head');if(!head||dqs('#bckRefreshData'))return;let actions=dqs('.top-actions',head);if(!actions){actions=document.createElement('div');actions.className='top-actions';head.append(actions)}const button=document.createElement('button');button.id='bckRefreshData';button.className='btn bck-data-refresh';button.type='button';const refreshLabel=currentView()==='analytics'?'Refresh analytics':'Refresh data';button.setAttribute('aria-label',refreshLabel);button.title=refreshLabel;button.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 7v5h-5M4 17v-5h5M6 7a7 7 0 0 1 12-1l2 6M4 12l2 6a7 7 0 0 0 12-1"/></svg>';actions.append(button);const notice=document.createElement('p');notice.id='bckDataNotice';notice.className='bck-data-notice';notice.setAttribute('role','status');head.after(notice);button.onclick=async()=>{if(button.disabled)return;button.disabled=true;button.setAttribute('aria-busy','true');notice.textContent='Refreshing data…';try{await loadLive();enhance();notice.textContent=preview()?'Preview data refreshed.':'Data refreshed.'}catch{notice.textContent='Could not refresh. Your previous data is still shown.'}finally{button.disabled=false;button.setAttribute('aria-busy','false')}};if(currentView()==='coupons')dqa('.page-head button,.toolbar button').filter(b=>b!==button&&b.textContent.trim().toLowerCase()==='refresh').forEach(b=>b.remove())}
function enhance(){refreshControl();placeBrandAndLanguage();enhanceOverview();enhanceCampaigns();enhanceQR();enhanceAnalytics();enhanceCoupons();enhanceCustomers();enhanceSettings();enhanceSupport();enhanceNotifications()}
document.addEventListener('click',e=>{interceptCampaignAction(e);interceptSaveCampaign(e)},true);
let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;observer.disconnect();try{enhance()}finally{observer.observe(document.documentElement,{childList:true,subtree:true})}})};const observer=new MutationObserver(ms=>{if(ms.some(m=>[...m.addedNodes].some(n=>n.nodeType===1)))schedule()});observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',bootstrap);setTimeout(bootstrap,0);
})();
