(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const V=()=>new URLSearchParams(location.search).get('view')||'overview';
const preview=()=>new URLSearchParams(location.search).get('preview')==='1';
let ctx={session:null,profile:null,campaigns:[]};
const LANGS={en:'English',hi:'हिन्दी',gu:'ગુજરાતી',mr:'मराठी',bn:'বাংলা'};
const D={
 hi:{Dashboard:'डैशबोर्ड',Campaigns:'कैंपेन',Coupons:'कूपन','QR Studio':'QR स्टूडियो',Analytics:'एनालिटिक्स',Customers:'ग्राहक',Settings:'सेटिंग्स',Notifications:'नोटिफिकेशन','Help & support':'मदद और सहायता','Business setup':'बिज़नेस सेटअप','Control account details, store identity and brand defaults.':'अकाउंट विवरण, स्टोर पहचान और ब्रांड डिफ़ॉल्ट नियंत्रित करें।','Business information':'बिज़नेस जानकारी','Owner name':'मालिक का नाम','Business name':'बिज़नेस नाम',Phone:'फोन',City:'शहर',Address:'पता','Brand defaults':'ब्रांड डिफ़ॉल्ट','Default campaign voice':'डिफ़ॉल्ट कैंपेन टोन','Save changes':'बदलाव सेव करें','QR fallback':'QR फ़ॉलबैक',Account:'अकाउंट','Report a Bug':'बग रिपोर्ट करें','Submit Feedback':'फीडबैक भेजें','Help & Support':'मदद और सहायता','Need help?':'मदद चाहिए?','Create campaign':'कैंपेन बनाएँ','Campaign details':'कैंपेन विवरण','Campaign name *':'कैंपेन नाम *',Description:'विवरण','Start date':'शुरू होने की तारीख','End date':'समाप्ति तारीख','Max plays / person':'प्रति व्यक्ति अधिकतम प्ले','Cooldown minutes':'कूलडाउन मिनट','Location / store':'लोकेशन / स्टोर','Redemption controls':'रिडेम्प्शन नियंत्रण','Choose games':'गेम चुनें','Customise games':'गेम कस्टमाइज़ करें','Permanent BCK QR':'स्थायी BCK QR','New campaign':'नया कैंपेन'},
 gu:{Dashboard:'ડેશબોર્ડ',Campaigns:'કેમ્પેઇન',Coupons:'કૂપન','QR Studio':'QR સ્ટુડિયો',Analytics:'એનલિટિક્સ',Customers:'ગ્રાહકો',Settings:'સેટિંગ્સ',Notifications:'નોટિફિકેશન્સ','Help & support':'મદદ અને સપોર્ટ','Business setup':'બિઝનેસ સેટઅપ','Control account details, store identity and brand defaults.':'એકાઉન્ટ વિગતો, સ્ટોર ઓળખ અને બ્રાન્ડ ડિફૉલ્ટ્સ નિયંત્રિત કરો.','Business information':'બિઝનેસ માહિતી','Owner name':'માલિકનું નામ','Business name':'બિઝનેસ નામ',Phone:'ફોન',City:'શહેર',Address:'સરનામું','Brand defaults':'બ્રાન્ડ ડિફૉલ્ટ્સ','Default campaign voice':'ડિફૉલ્ટ કેમ્પેઇન ટોન','Save changes':'ફેરફારો સેવ કરો','QR fallback':'QR ફૉલબૅક',Account:'એકાઉન્ટ','Report a Bug':'બગ રિપોર્ટ કરો','Submit Feedback':'ફીડબૅક મોકલો','Help & Support':'મદદ અને સપોર્ટ','Need help?':'મદદ જોઈએ?','Create campaign':'કેમ્પેઇન બનાવો','Campaign details':'કેમ્પેઇન વિગતો','Campaign name *':'કેમ્પેઇન નામ *',Description:'વર્ણન','Start date':'શરૂઆત તારીખ','End date':'અંત તારીખ','Max plays / person':'પ્રતિ વ્યક્તિ મહત્તમ પ્લે','Cooldown minutes':'કૂલડાઉન મિનિટ','Location / store':'લોકેશન / સ્ટોર','Redemption controls':'રિડેમ્પ્શન નિયંત્રણ','Choose games':'ગેમ પસંદ કરો','Customise games':'ગેમ કસ્ટમાઇઝ કરો','Permanent BCK QR':'સ્થાયી BCK QR','New campaign':'નવું કેમ્પેઇન'},
 mr:{Dashboard:'डॅशबोर्ड',Campaigns:'कॅम्पेन',Coupons:'कूपन','QR Studio':'QR स्टुडिओ',Analytics:'अॅनालिटिक्स',Customers:'ग्राहक',Settings:'सेटिंग्ज',Notifications:'नोटिफिकेशन्स','Help & support':'मदत व सपोर्ट','Business setup':'बिझनेस सेटअप','Business information':'बिझनेस माहिती','Owner name':'मालकाचे नाव','Business name':'बिझनेस नाव',Phone:'फोन',City:'शहर',Address:'पत्ता','Brand defaults':'ब्रँड डिफॉल्ट्स','Save changes':'बदल सेव्ह करा','QR fallback':'QR फॉलबॅक',Account:'अकाउंट','Report a Bug':'बग रिपोर्ट करा','Submit Feedback':'फीडबॅक पाठवा','Need help?':'मदत हवी?','Create campaign':'कॅम्पेन तयार करा','Campaign details':'कॅम्पेन तपशील','Choose games':'गेम निवडा','Customise games':'गेम कस्टमाइज करा','New campaign':'नवीन कॅम्पेन'},
 bn:{Dashboard:'ড্যাশবোর্ড',Campaigns:'ক্যাম্পেইন',Coupons:'কুপন','QR Studio':'QR স্টুডিও',Analytics:'অ্যানালিটিক্স',Customers:'গ্রাহক',Settings:'সেটিংস',Notifications:'নোটিফিকেশন','Help & support':'সহায়তা ও সাপোর্ট','Business setup':'বিজনেস সেটআপ','Business information':'বিজনেস তথ্য','Owner name':'মালিকের নাম','Business name':'বিজনেস নাম',Phone:'ফোন',City:'শহর',Address:'ঠিকানা','Brand defaults':'ব্র্যান্ড ডিফল্ট','Save changes':'পরিবর্তন সেভ করুন','QR fallback':'QR ফলব্যাক',Account:'অ্যাকাউন্ট','Report a Bug':'বাগ রিপোর্ট করুন','Submit Feedback':'ফিডব্যাক দিন','Need help?':'সহায়তা দরকার?','Create campaign':'ক্যাম্পেইন তৈরি করুন','Campaign details':'ক্যাম্পেইন বিস্তারিত','Choose games':'গেম বেছে নিন','Customise games':'গেম কাস্টমাইজ করুন','New campaign':'নতুন ক্যাম্পেইন'}
};
function toast(t){let e=$('#premiumToast');if(!e){e=document.createElement('div');e.id='premiumToast';e.className='bck-v2-toast';document.body.append(e)}e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
async function loadCtx(){if(preview()){ctx.profile={business_name:'BCK Preview',owner_name:'Preview Merchant',phone:'',city:'',address:'',email:'preview@getbck.com'};return}const {data:{session}}=await client.auth.getSession();ctx.session=session;if(!session)return;const [p,c]=await Promise.all([client.from('profiles').select('*').eq('id',session.user.id).maybeSingle(),client.from('campaigns').select('*').eq('merchant_id',session.user.id).order('created_at',{ascending:false})]);ctx.profile=p.data||{};ctx.profile.email=session.user.email;ctx.campaigns=c.data||[]}
function modal(html){$('.premium-modal')?.remove();const m=document.createElement('div');m.className='premium-modal';m.innerHTML=`<section class="premium-card">${html}<button class="premium-close" aria-label="Close">×</button></section>`;document.body.append(m);$('.premium-close',m).onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()};return m}
function openStore(){const p=ctx.profile||{},active=ctx.campaigns.find(c=>c.status==='active');const m=modal(`<h2>${p.business_name||'Store profile'}</h2><div class="premium-profile-head">${p.logo_url?`<img src="${p.logo_url}" alt="Store logo">`:'<div class="premium-profile-placeholder">S</div>'}<div><strong>${p.business_name||'Your store'}</strong><small>${active?`Live campaign: ${active.name}`:'No campaign currently live'}</small></div></div><div class="premium-detail-grid"><div class="premium-detail"><small>Owner</small><strong>${p.owner_name||'—'}</strong></div><div class="premium-detail"><small>Phone</small><strong>${p.phone||'—'}</strong></div><div class="premium-detail"><small>City</small><strong>${p.city||'—'}</strong></div><div class="premium-detail"><small>Address</small><strong>${p.address||'—'}</strong></div></div><div class="premium-actions"><button class="btn" data-store-settings>Edit store details</button><button class="btn ink" data-store-qr>Open QR Studio</button></div>`);$('[data-store-settings]',m).onclick=()=>{m.remove();goView('settings')};$('[data-store-qr]',m).onclick=()=>{m.remove();goView('qr')}}
function openAccount(){const email=ctx.session?.user?.email||ctx.profile?.email||'Signed in';const m=modal(`<h2>Account</h2><p>Manage your BCK account without turning the email tile into another Settings shortcut.</p><div class="premium-account-email">${email}</div><div class="premium-actions"><button class="btn" data-account-profile>Business settings</button><button class="btn" data-account-support>Help & support</button><button class="btn ink" data-account-out>Sign out</button></div>`);$('[data-account-profile]',m).onclick=()=>{m.remove();goView('settings')};$('[data-account-support]',m).onclick=()=>{m.remove();goView('support')};$('[data-account-out]',m).onclick=async()=>{if(!preview())await client.auth.signOut();location.href='auth.html'}}
function goView(v){try{go(v)}catch{location.href=`dashboard.html?view=${v}`}}
function bindSidebar(){const chip=$('.store-chip'),user=$('.side-user');if(chip&&!chip.dataset.premium){chip.dataset.premium='1';chip.title='Open store profile';chip.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();openStore()}}if(user&&!user.dataset.premium){user.dataset.premium='1';user.title='Open account menu';user.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();openAccount()}}}
function translate(){const code=localStorage.getItem('bck_language')||'en';document.documentElement.lang=code;const dict=D[code];if(!dict)return;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(n.parentElement?.closest('script,style,input,textarea,select,option'))return;const t=n.nodeValue.trim();if(dict[t])n.nodeValue=n.nodeValue.replace(t,dict[t])});document.body.classList.add('translate-pulse');setTimeout(()=>document.body.classList.remove('translate-pulse'),250)}
function bindLanguage(){const menu=$('#bckLanguage');if(!menu||menu.dataset.premiumLang)return;menu.dataset.premiumLang='1';menu.addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b)return;setTimeout(translate,20)},true)}
function removeSettingsFeedback(){if(V()!=='settings')return;$('.settings-grid aside>.bck-support-actions')?.remove()}
const FAQ=[
 ['Getting started',[['How do I create my first campaign?','Open Campaigns → New campaign. Add the campaign details, choose at least one game, customise rewards and probabilities, then save as Draft or launch it.'],['Can I run multiple games?','Yes. One campaign may contain multiple games. You can set how often each selected game is shown using Game Probability.'],['Can more than one campaign be live at once?','No. BCK keeps one permanent QR per merchant and routes it to one active campaign at a time. Activating another campaign pauses the previous one.'],['What happens if I pause the active campaign?','The QR still works. Customers see your branded fallback screen, optional menu button and optional fallback link until another campaign is activated.']]],
 ['QR & customer experience',[['Do I need to print a new QR for every campaign?','No. Your permanent BCK QR stays the same. Only the campaign behind it changes.'],['Can I add my menu to the customer screen?','Yes. Add a Menu URL in Settings. Customers will see a Menu button before they start playing.'],['What does QR fallback mean?','Fallback is the branded screen shown when no campaign is active. You can customise its message and optionally send customers to your menu or website.']]],
 ['Games & rewards',[['What is Instant vs Come-BCK?','Instant rewards are used on the current visit. Come-BCK rewards are intended for a later visit.'],['What does Hybrid do?','Hybrid lets different prizes inside the same campaign use different reward types.'],['What does game probability control?','It controls how often each selected game is presented when a campaign has multiple games. The total should equal 100%.'],['Can I customise each game?','Yes. Reward labels, codes, odds, thresholds, board size and other game-specific controls can be configured in the Customise step.']]],
 ['Coupons & controls',[['What is manual redemption?','Staff redeems a coupon from the merchant dashboard. This is the safer default for in-store rewards.'],['What is automatic redemption?','When enabled, the customer result screen may provide the redemption action. Use it only where staff verification is not required.'],['Can coupon codes be copied?','Yes. You can allow or disable code copy per campaign.'],['Can rewards expire automatically?','Yes. Enable automatic expiry and set the expiry duration.']]],
 ['Analytics & customers',[['What updates live?','Scans, plays, wins, coupon issuance, redemptions and tracked returns feed the merchant dashboard and analytics.'],['How are repeat customers counted?','BCK uses an anonymous visitor identifier. A later scan from the same identifier can be recorded as a return without requiring the customer to create an account.'],['Why do some metrics show zero?','BCK does not invent data. A metric remains zero until a corresponding real event is recorded.']]],
 ['Account & privacy',[['Can customers play without installing an app?','Yes. Games run in the mobile browser after scanning the QR.'],['Does changing dashboard language change my customer campaign?','Dashboard language is a merchant preference. Customer-facing language can be selected independently on the play screen.'],['Where can I report a problem?','Use Report a Bug in Help & support. You can describe the problem and attach a screenshot.']]]
];
function support(){if(V()!=='support')return;const content=$('.content');if(!content||content.dataset.premiumSupport)return;content.dataset.premiumSupport='1';const existing=$('.bck-support-actions',content);if(existing)content.prepend(existing);$$('.content>.panel,.content>.faq-section,.content .accordion').forEach(x=>{if(!x.closest('.bck-support-actions'))x.remove()});const wrap=document.createElement('div');wrap.className='support-faq-wrap';wrap.innerHTML=FAQ.map(([title,items])=>`<div><div class="faq-section-label">${title}</div><div class="faq-group">${items.map(([q,a])=>`<div class="faq-item"><button class="faq-q"><span>${q}</span><span>⌄</span></button><div class="faq-a">${a}</div></div>`).join('')}</div></div>`).join('');content.append(wrap);$$('.faq-q',wrap).forEach(q=>q.onclick=()=>{const item=q.closest('.faq-item'),was=item.classList.contains('open');$$('.faq-item',wrap).forEach(x=>x.classList.remove('open'));if(!was)item.classList.add('open')})}
function builder(){if(V()!=='new-campaign')return;const s1=$('.wizard-panel[data-step="1"]');if(s1&&!$('.builder-pro-settings',s1)){const box=document.createElement('section');box.className='builder-pro-settings';box.innerHTML=`<h3>Coupon & redemption settings</h3><p>Control how rewards are redeemed after customers win.</p><div class="pro-grid"><div class="pro-card"><strong>Redemption mode</strong><small>Manual keeps redemption with staff. Automatic exposes a customer-side redeem action.</small><div class="segmented"><button class="active" data-red-mode="manual">Manual</button><button data-red-mode="automatic">Automatic</button></div></div><div class="pro-card"><strong>Coupon auto-expiry</strong><small>Expire rewards automatically after a set window.</small><div class="duration-row"><input id="premiumExpiry" type="number" min="1" max="8760" value="168"><span>hours</span></div></div><div class="pro-card"><strong>Allow code copy</strong><small>Customers can copy the coupon code from the result screen.</small><div class="segmented"><button class="active" data-copy="yes">Yes</button><button data-copy="no">No</button></div></div><div class="pro-card"><strong>Save reward card</strong><small>Customer can save a clean reward card image for later.</small><div class="segmented"><button data-image="yes">Yes</button><button class="active" data-image="no">No</button></div></div></div>`;const old=$('.panel.form-section:not(.violet)',s1);if(old)old.replaceWith(box);else s1.insertBefore(box,$('.wizard-actions',s1));$$('.segmented button',box).forEach(b=>b.onclick=()=>{[...b.parentElement.children].forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
 const s2=$('.wizard-panel[data-step="2"]');if(s2&&s2.classList.contains('active')&&!$('.game-probability',s2)){const selected=$$('.choice.selected[data-game]',s2);if(selected.length){const box=document.createElement('section');box.className='game-probability';const even=Math.floor(100/selected.length),vals=selected.map((x,i)=>i===selected.length-1?100-even*(selected.length-1):even);box.innerHTML=`<h3>Game Probability</h3><p>Set how often each selected game is shown to customers.</p>${selected.map((x,i)=>`<div class="prob-row"><strong>${x.dataset.game}</strong><input type="range" min="0" max="100" value="${vals[i]}" data-prob="${x.dataset.game}"><output>${vals[i]}%</output></div>`).join('')}<div class="prob-total">Total: 100%</div>`;s2.insertBefore(box,$('.wizard-actions',s2));$$('[data-prob]',box).forEach(r=>r.oninput=()=>{r.nextElementSibling.textContent=r.value+'%';const total=$$('[data-prob]',box).reduce((n,x)=>n+(+x.value||0),0),o=$('.prob-total',box);o.textContent=`Total: ${total}%`;o.classList.toggle('bad',total!==100)})}}}
function settingsExtra(){if(V()!=='settings')return;const main=$('.settings-grid>div')||$('.settings-grid');if(!main||$('.settings-extra-card'))return;const card=document.createElement('section');card.className='settings-extra-card';card.innerHTML=`<h3>Customer landing screen</h3><p>Shown after the QR scan before the customer starts a game.</p><div class="field"><label>Menu URL</label><input id="premiumMenuUrl" type="url" placeholder="https://yourmenu.com" value="${ctx.profile?.menu_url||''}"></div><div class="field"><label>Welcome line</label><input id="premiumWelcome" maxlength="100" value="${ctx.profile?.customer_welcome_message||'A quick game. A real reward. Ready?'}"></div><div class="field"><label>Play button text</label><input id="premiumCta" maxlength="32" value="${ctx.profile?.landing_cta_text||'Play & win'}"></div>`;main.append(card);const save=$('#settingsForm');if(save&&!save.dataset.premiumExtra){save.dataset.premiumExtra='1';save.addEventListener('submit',async()=>{if(preview())return;const payload={menu_url:$('#premiumMenuUrl')?.value.trim()||null,customer_welcome_message:$('#premiumWelcome')?.value.trim()||null,landing_cta_text:$('#premiumCta')?.value.trim()||'Play & win'};await client.from('profiles').update(payload).eq('id',ctx.session.user.id);Object.assign(ctx.profile,payload)},false)}}
function campaigns(){if(V()!=='campaigns')return;$$('.campaign-row').forEach(r=>{if(!$('.premium-live-note',r)){const status=$('.status',r)?.textContent.trim().toLowerCase(),n=document.createElement('div');n.className=`premium-live-note ${status==='active'?'active':''}`;n.innerHTML=`<i></i>${status==='active'?'Serving the permanent QR':'Not currently serving QR'}`;const first=$('div',r);first?.append(n)}})}
function run(){bindSidebar();bindLanguage();removeSettingsFeedback();support();builder();settingsExtra();campaigns();translate()}
async function boot(){await loadCtx();run();let q=false;new MutationObserver(ms=>{if(q||!ms.some(m=>[...m.addedNodes].some(n=>n.nodeType===1)))return;q=true;requestAnimationFrame(()=>{q=false;run()})}).observe(document.documentElement,{childList:true,subtree:true})}
document.addEventListener('DOMContentLoaded',boot);setTimeout(boot,80);
})();