const menuBtn=document.getElementById('menuBtn'),mobileNav=document.getElementById('mobileNav');if(menuBtn)menuBtn.onclick=()=>mobileNav.classList.toggle('open');
const modal=document.getElementById('gameModal'),body=document.getElementById('gameBody'),title=document.getElementById('gameTitle'),close=document.getElementById('closeGame');
const rewards=['Free brownie today','10% off this bill','₹100 off your next visit','Free cold coffee next visit','Dessert upgrade today'];
const rand=a=>a[Math.floor(Math.random()*a.length)];
function resultBox(text='Ready when you are.') {return `<div class="game-result" id="result">${text}</div>`}
function openGame(type){modal.classList.add('open');document.body.style.overflow='hidden';renderGame(type)}
function closeGame(){modal.classList.remove('open');document.body.style.overflow='';body.innerHTML=''}
close.onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeGame()});document.querySelectorAll('.game-card').forEach(c=>c.onclick=()=>openGame(c.dataset.game));
function renderGame(type){
 if(type==='wheel'){title.textContent='Spin the Wheel';body.innerHTML=`<div class="game-stage"><div class="big-wheel" id="wheel"></div><button class="btn accent" id="play">SPIN</button>${resultBox('Sample campaign — tap spin.')}</div>`;let r=0;document.getElementById('play').onclick=()=>{r+=1440+Math.floor(Math.random()*360);wheel.style.transform=`rotate(${r}deg)`;result.textContent='Spinning…';setTimeout(()=>result.textContent='You won: '+rand(rewards),2200)}}
 if(type==='lottery'){title.textContent='Instant Lottery';body.innerHTML=`<div class="game-stage"><div class="lottery-box"><span id="lotteryReward">${rand(rewards)}</span><div class="scratch-layer" id="scratch">SCRATCH TO REVEAL</div></div>${resultBox('Tap the scratch panel.')}</div>`;scratch.onclick=()=>{scratch.style.display='none';result.textContent='Reward revealed.'}}
 if(type==='slots'){title.textContent='Slot Machine';body.innerHTML=`<div class="game-stage"><div class="slot-large"><span id="s1">☕</span><span id="s2">🍰</span><span id="s3">✦</span></div><button class="btn accent" id="play">ROLL</button>${resultBox('Match the reels.')}</div>`;const icons=['☕','🍰','✦','🍕','🥤'];play.onclick=()=>{let n=0;result.textContent='Rolling…';const iv=setInterval(()=>{s1.textContent=rand(icons);s2.textContent=rand(icons);s3.textContent=rand(icons);if(++n>12){clearInterval(iv);const win=Math.random()>.45;if(win){const x=rand(icons);s1.textContent=s2.textContent=s3.textContent=x;result.textContent='You won: '+rand(rewards)}else result.textContent='So close — demo outcome: try again.'}},90)}}
 if(type==='catch'){title.textContent='Catch & Win';body.innerHTML=`<div class="game-stage"><div class="catch-area" id="area"><button class="catch-target" id="target">+1</button></div><button class="btn accent" id="play">START 8s</button>${resultBox('Catch 5 tokens to win.')}</div>`;let score=0,timer=null;function move(){target.style.left=Math.random()*(area.clientWidth-52)+'px';target.style.top=Math.random()*(area.clientHeight-52)+'px'}target.onclick=()=>{if(!timer)return;score++;result.textContent=`${score}/5 caught`;move();if(score>=5){clearTimeout(timer);timer=null;result.textContent='You won: '+rand(rewards)}};play.onclick=()=>{score=0;result.textContent='0/5 caught';move();timer=setTimeout(()=>{timer=null;if(score<5)result.textContent=`Time! You caught ${score}/5 — try again.`},8000)}}
 if(type==='snake'){title.textContent='Snakes & Ladders';let cells='';for(let i=25;i>=1;i--)cells+=`<div class="snake-cell" data-n="${i}">${i}</div>`;body.innerHTML=`<div class="game-stage"><div class="snake-board" id="board">${cells}</div><button class="btn accent" id="play">ROLL DICE</button>${resultBox('One quick roll. Land on a reward tile.')}</div>`;let pos=1;function mark(){document.querySelectorAll('.snake-cell').forEach(c=>c.classList.toggle('player',Number(c.dataset.n)===pos));const p=document.querySelector('.snake-cell.player');if(p)p.textContent='●'}mark();play.onclick=()=>{const d=1+Math.floor(Math.random()*6);pos=Math.min(25,pos+d);mark();result.textContent=`You rolled ${d}. ${pos>=8?'Reward unlocked: '+rand(rewards):'Move again to reach the reward zone.'}`}}
 if(type==='tap'){title.textContent='Tap Speed';body.innerHTML=`<div class="game-stage"><button class="tap-btn" id="tap">TAP</button><button class="btn secondary" id="play">START 5s</button>${resultBox('Hit 25 taps in five seconds.')}</div>`;let c=0,live=false;tap.onclick=()=>{if(live){c++;tap.textContent=c}};play.onclick=()=>{c=0;live=true;tap.textContent='0';result.textContent='Go!';setTimeout(()=>{live=false;result.textContent=c>=25?'You won: '+rand(rewards):`${c} taps — hit 25 to win.`},5000)}}
}

async function bckAuthAwareNav(){const navright=document.querySelector('.navright');if(!navright)return;navright.style.minWidth='215px';try{if(!window.supabase){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=reject;document.head.append(s)})}const client=supabase.createClient('https://uxsejwqzxmftyqfncmgf.supabase.co','sb_publishable_7jNw8dRPfmzGo8xJ6SXo-w_rivj0GKd'),{data:{session}}=await client.auth.getSession();if(!session)return;navright.querySelector('.signin-link')?.remove();navright.querySelector('a.btn.primary.small')?.remove();const d=document.createElement('a');d.className='btn primary small';d.href='dashboard.html?view=overview';d.textContent='Dashboard →';navright.insertBefore(d,document.getElementById('menuBtn'));if(mobileNav){[...mobileNav.querySelectorAll('a')].filter(a=>/^(Sign in|Start free)$/i.test(a.textContent.trim())).forEach(a=>a.remove());const m=document.createElement('a');m.className='btn primary';m.href='dashboard.html?view=overview';m.textContent='Dashboard →';mobileNav.append(m)}}catch(e){console.warn('BCK auth CTA check unavailable',e)}}
document.addEventListener('DOMContentLoaded',bckAuthAwareNav);